glyph_offset:
    x: 0
    y: -1

font:
    normal:
        family: MesloLGS Nerd Font
        style: Regular
    bold:
        family: MesloLGS Nerd Font
        style: Bold
    italic:
        family: MesloLGS Nerd Font
        style: Italic

    # Point size of the font
    size: 8

env:
    TERM: xterm-256color

# Colors (Nord)
colors:
    # Default colors
    primary:
        background: '0x212733'
        foreground: '0xD9D7CE'
  
    # Normal colors
    normal:
        black:   '0x1F2430'
        red:     '0xFF3333'
        green:   '0xBAE67E'
        yellow:  '0xFFD580'
        blue:    '0x73D0FF'
        magenta: '0xF28779'
        cyan:    '0x95E6CB'
        white:   '0xFFFFFF'
  
    # Bright colors
    bright:
        black:   '0x292B30'
        red:     '0xFF6666'
        green:   '0xCEE6AC'
        yellow:  '0xFFE6B3'
        blue:    '0xA6E1FF'
        magenta: '0xFFD6DA'
        cyan:    '0xFFFFFF'
        white:   '0xFFFFFF'

window:
    padding:
        x: 4
        y: 4
