glyph_offset:
    x: 0
    y: -1

font:
    normal:
        family: MesloLGS Nerd Font
        style: Regular
    bold:
        family: MesloLGS Nerd Font
        style: Bold
    italic:
        family: MesloLGS Nerd Font
        style: Italic

    # Point size of the font
    size: 8

env:
    TERM: xterm-256color

# Colors (Nord)
colors:
    # Default colors
    primary:
        background: '0x2E3440'
        foreground: '0xD8DEE9'
  
    # Normal colors
    normal:
        black:   '0x3B4252'
        red:     '0xBF616A'
        green:   '0xA3BE8C'
        yellow:  '0xEBCB8B'
        blue:    '0x81A1C1'
        magenta: '0xB48EAD'
        cyan:    '0x88C0D0'
        white:   '0xE5E9F0'
  
    # Bright colors
    bright:
        black:   '0x4C566A'
        red:     '0xBF616A'
        green:   '0xA3BE8C'
        yellow:  '0xEBCB8B'
        blue:    '0x81A1C1'
        magenta: '0xB48EAD'
        cyan:    '0x8FBCBB'
        white:   '0xECEFF4'
